[theme]
primaryColor = "#60269D"                # PhonePe purple (brand color)
backgroundColor = "#e4c9ff"           # White background for a clean, modern look
secondaryBackgroundColor = "#b774fc"    # Light grey for subtle contrast
textColor = "60269D"                   # Dark grey text for readability
font = "sans serif"                     # Clean and professional font style
